name: pdfx
description: Flutter plugin to render & show PDF pages as images on Web, MacOS, Windows, Android and iOS.
repository: https://github.com/ScerIO/packages.flutter/tree/main/packages/pdfx
issue_tracker: https://github.com/ScerIO/packages.flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+pdfx%22
version: 2.5.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
  js: ^0.6.7
  device_info_plus: ^11.1.0
  uuid: ^4.4.0
  meta: ^1.9.1
  extension: ^0.6.0
  synchronized: ^3.1.0
  universal_platform: ^1.0.0+1
  photo_view: ^0.15.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pigeon: ^19.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.scer.pdfx
        pluginClass: PdfxPlugin
      ios:
        pluginClass: PdfxPlugin
      macos:
        pluginClass: PdfxPlugin
      windows:
        pluginClass: PdfxPlugin
      web:
        pluginClass: PdfxPlugin
        fileName: src/renderer/web/pdfx_plugin.dart
